
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'BC1AE1C57792C98FDFEA7D932A7384C8'
    
_lr_action_items = {'TIEMPO':([10,],[16,]),'d':([16,],[20,]),')':([15,17,18,],[19,23,24,]),'(':([3,6,],[9,12,]),'-':([1,16,19,23,24,27,],[7,21,25,30,32,36,]),'MODOOCTAVA':([12,],[17,]),'|':([0,1,5,7,8,16,19,21,22,23,24,25,26,27,30,31,32,33,36,37,],[5,8,5,5,5,22,26,5,5,31,33,5,5,37,5,5,5,5,5,5,]),'NOTA':([0,5,7,8,21,22,25,26,30,31,32,33,36,37,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'INSTRUMENTO':([0,5,7,8,21,22,25,26,30,31,32,33,36,37,],[3,3,3,3,3,3,3,3,3,3,3,3,3,3,]),'t':([4,],[10,]),'DURACION':([20,],[27,]),'MODODURACION':([12,],[18,]),'MOD':([0,5,7,8,21,22,25,26,30,31,32,33,36,37,],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'CAMBIOINSTRUMENTO':([9,],[15,]),'MODOTEMPO':([0,5,7,8,21,22,25,26,30,31,32,33,36,37,],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,]),'$end':([0,1,2,5,7,8,11,13,14,16,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,],[-20,-18,0,-20,-20,-20,-19,-16,-17,-6,-15,-20,-20,-9,-12,-20,-20,-3,-4,-5,-20,-20,-20,-20,-13,-14,-20,-20,-7,-8,-10,-11,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,5,7,8,21,22,25,26,30,31,32,33,36,37,],[2,11,13,14,28,29,34,35,38,39,40,41,42,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> NOTA t TIEMPO d DURACION - S','S',7,'p_notasConDuracion','ProyectoAutomatas.py',298),
  ('S -> NOTA t TIEMPO d DURACION | S','S',7,'p_notasConDuracion','ProyectoAutomatas.py',299),
  ('S -> NOTA t TIEMPO d DURACION','S',5,'p_notasConDuracion','ProyectoAutomatas.py',300),
  ('S -> NOTA t TIEMPO - S','S',5,'p_notasSinDuracion','ProyectoAutomatas.py',309),
  ('S -> NOTA t TIEMPO | S','S',5,'p_notasSinDuracion','ProyectoAutomatas.py',310),
  ('S -> NOTA t TIEMPO','S',3,'p_notasSinDuracion','ProyectoAutomatas.py',311),
  ('S -> MOD ( MODOOCTAVA ) - S','S',6,'p_cambioOctava','ProyectoAutomatas.py',322),
  ('S -> MOD ( MODOOCTAVA ) | S','S',6,'p_cambioOctava','ProyectoAutomatas.py',323),
  ('S -> MOD ( MODOOCTAVA )','S',4,'p_cambioOctava','ProyectoAutomatas.py',324),
  ('S -> MOD ( MODODURACION ) - S','S',6,'p_cambioDuracion','ProyectoAutomatas.py',329),
  ('S -> MOD ( MODODURACION ) | S','S',6,'p_cambioDuracion','ProyectoAutomatas.py',330),
  ('S -> MOD ( MODODURACION )','S',4,'p_cambioDuracion','ProyectoAutomatas.py',331),
  ('S -> INSTRUMENTO ( CAMBIOINSTRUMENTO ) - S','S',6,'p_cambioInstrumento','ProyectoAutomatas.py',339),
  ('S -> INSTRUMENTO ( CAMBIOINSTRUMENTO ) | S','S',6,'p_cambioInstrumento','ProyectoAutomatas.py',340),
  ('S -> INSTRUMENTO ( CAMBIOINSTRUMENTO )','S',4,'p_cambioInstrumento','ProyectoAutomatas.py',341),
  ('S -> MODOTEMPO - S','S',3,'p_cambioTempo','ProyectoAutomatas.py',363),
  ('S -> MODOTEMPO | S','S',3,'p_cambioTempo','ProyectoAutomatas.py',364),
  ('S -> MODOTEMPO','S',1,'p_cambioTempo','ProyectoAutomatas.py',365),
  ('S -> | S','S',2,'p_separacionCompas','ProyectoAutomatas.py',373),
  ('S -> <empty>','S',0,'p_vacio','ProyectoAutomatas.py',378),
]
